const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),E=require('./engine.js');
const cards=vm.runInNewContext(fs.readFileSync(__dirname+'/cards.js','utf8')+';CARDS');
for(let pos=1;pos<=9;pos++)for(const t of cards){assert.equal(E.canTake(pos,t),t.side==='light'?t.value>pos:t.value<pos);assert.equal(E.move(pos,t),E.canTake(pos,t)?t.value:pos);}
const s=E.create(cards);assert.equal(s.board.filter(Boolean).length,1);assert.equal(s.compass,s.board[24].value);assert.deepEqual(s.board.map((_,i)=>i).filter(i=>E.valid(s.board,i)),[17,23,25,31]);
s.compass=7;s.batteries=2;const selected=s.offers.shadow.find(t=>t.value===5);s.selected=selected||null;const offers=JSON.stringify(s.offers);assert(E.spendBattery(s));assert.equal(s.compass,6);assert.equal(s.batteries,1);assert.equal(JSON.stringify(s.offers),offers);assert(E.spendBattery(s));assert(!E.spendBattery(s));s.batteries=2;s.compass=1;assert(!E.spendBattery(s));assert.equal(s.batteries,2);
let board=Array(49).fill(null);board[24]=cards[0];board[23]=cards[1];board[22]=cards[2];board[21]=cards[3];assert(!E.valid(board,25));assert(E.valid(board,17));assert(!E.valid(board,0));assert(!E.valid(board,-1));
let completed=0,blocked=0;
for(let run=0;run<200;run++){const state=E.create(cards);while(state.board.filter(Boolean).length<16){const legal=[...state.offers.light,...state.offers.shadow].filter(t=>E.canTake(state.compass,t));if(!legal.length){if(E.spendBattery(state))continue;blocked++;break;}state.selected=legal[Math.floor(Math.random()*legal.length)];const positions=state.board.map((_,p)=>p).filter(p=>E.valid(state.board,p));assert(positions.length);const expected=state.selected.value;assert(E.place(state,positions[Math.floor(Math.random()*positions.length)]));assert.equal(state.compass,expected);assert.equal(state.offers.light.length,4);assert.equal(state.offers.shadow.length,4);assert(Number.isFinite(E.score(state.board)));const all=[...state.board.filter(Boolean),...state.offers.light,...state.offers.shadow,...state.decks.light,...state.decks.shadow];assert.equal(all.length,86);assert.equal(new Set(all.map(t=>t.id)).size,86);const b=E.bounds(state.board);assert(b.right-b.left<4&&b.bottom-b.top<4);}if(state.board.filter(Boolean).length===16){completed++;assert(!E.spendBattery(state));}}
console.log(`OK: 200 simulazioni (${completed} complete, ${blocked} senza mosse); direzioni, Batterie, crescita 4x4, 86 tessere conservate.`);
